# Generated by Django 5.2.7 on 2025-10-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('idPuesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePuesto', models.CharField(max_length=100)),
                ('salarioHoraPuesto', models.FloatField()),
                ('salarioDiarioPuesto', models.FloatField()),
                ('salarioMesPuesto', models.FloatField()),
            ],
        ),
    ]
