# Generated by Django 5.2.7 on 2025-11-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='administrativo',
            field=models.BooleanField(default=False),
        ),
    ]
