# Generated by Django 5.2.7 on 2025-11-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0002_puesto_administrativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='salarioDiarioPuesto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='salarioHoraPuesto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='salarioMesPuesto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
