# Generated by Django 5.2.7 on 2025-11-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0003_alter_puesto_salariodiariopuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='nombrePuesto',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
