# Generated by Django 5.2.7 on 2025-11-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_transaccion_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='nro_transaccion',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
