# Generated by Django 5.2.7 on 2025-11-01 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_carga_inicial_cuentas'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodos.periodocontable')),
            ],
            options={
                'unique_together': {('cuenta', 'periodo')},
            },
        ),
    ]
