# Generated by Django 5.2.7 on 2025-11-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0002_saldocuenta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaldoCuenta',
        ),
    ]
