# Generated by Django 5.2.7 on 2025-11-11 17:22

from django.db import migrations
from datetime import date,timedelta

def establecer_periodo_inicial(apps, schema_editor):
    PeriodoContable = apps.get_model('periodos', 'PeriodoContable')
    Transaccion = apps.get_model('transacciones', 'Transaccion')
    fecha_hoy = date.today()
    fecha_fin = fecha_hoy + timedelta(days=5)
    
    periodo_inicial, creado = PeriodoContable.objects.get_or_create(
        nombre='Periodo Inicial',
        defaults={
            'fecha_inicio': fecha_hoy,
            'fecha_fin': fecha_fin
        }
    )
    #contantes de montos 
    Mobiliario_oficina=3130.00
    Equipo_computo_redes=15330.00
    SW_herramientas =2000.00
    Papeleria_suministros=72.50
    Otros_equipos = 375.00
    Capital_social = Mobiliario_oficina + Equipo_computo_redes + SW_herramientas + Papeleria_suministros + Otros_equipos
    
    #crear la transaccion
    Transaccion.objects.get_or_create(
        descripcion='Transacción Inicial para el Período Inicial',
        fecha=fecha_hoy,
        monto=Capital_social,
        periodo=periodo_inicial
    )


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0003_delete_saldocuenta'),
    ]

    operations = [
    ]
