# Generated by Django 5.2.7 on 2025-10-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codSubTipoCuenta', models.CharField(max_length=10, unique=True)),
                ('nombreSubCuenta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codTipoCuenta', models.CharField(max_length=10, unique=True)),
                ('nombreRubro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCuenta', models.CharField(max_length=10, unique=True)),
                ('nombreCuenta', models.CharField(max_length=100)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subTipoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='cuentas.subtipocuenta')),
            ],
        ),
        migrations.AddField(
            model_name='subtipocuenta',
            name='tipoCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='cuentas.tipocuenta'),
        ),
    ]
