# Generated by Django 5.2.7 on 2025-11-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_carga_inicial_cuentas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='saldo_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
